### PR TITLE
FIX jspsych

### PR DESCRIPTION
**Pull request by andrewheusser**
jspsych now works. To test, run ReactionTimeTask

### CODE REVIEW

**Comment by teonbrooks** [comment]
cool, you'll need a rebase, also your commit history is a little funky

**Comment by andrewheusser** [comment]
so, i rebase my fork and then submit another pull request or will it just update this one?

**Comment by teonbrooks** [comment]
the rebase and push will update here. you will have to rebase from `upstream/master` instead of master since your pr is from master

**Comment by teonbrooks** [comment]
LGTM. thanks @andyh616!

**Pull request merged**
