### PR TITLE
updated controllers naming and moved experiments logic inside controller

### PR DESCRIPTION
**Pull request by tashoecraft**
We had all of the controllers named 'HomeCtrl', which isn't what we want. Each definition of a controller gets a new name, and unless you are using identical logic in two places (which is incredible unlikely) just make a new controller and give it a unique name. I also placed the experiments logic inside of the controller as any javascript that controls a section/the page like that should be in the controller. Never do <script> Javascript in here </script> .

### CODE REVIEW

**Comment by andrewheusser** [comment]
looks good...before merging..have you tested the experiements to see if they run properly with the code now in the controller?

**Comment by tashoecraft** [comment]
Only the reaction time task is available and it works. The other one doesn't have a link yet too it, it also has socket.io code in it and that isn't hooked up so it would error anyway.

**Comment by andrewheusser** [comment]
ah thats right, ok cool!

**Comment by teonbrooks** [comment]
@tashoecraft, since the template for experiments are all the same, could we use a common template across them instead of having the small individual html files? for instance, `client/app/experiments/triggerTest/triggerTest.html` is only two lines now, and is basically the same as `client/app/experiments/reactionTimeTask/reactionTimeTask.html`

**Pull request merged**
